version: '3.8'

services:
  network-scanner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: network-security-scanner
    network_mode: host
    # network_mode: host permite acesso completo à rede do host

    volumes:
      - ./reports:/app/reports
      - ./logs:/app/logs

    environment:
      - SCANNER_VERSION=2.0
      - SCAN_TIMEOUT=300
      - NETWORK_RANGE=auto

    restart: unless-stopped

    # Entrypoint personalizado
    entrypoint: ["/app/entrypoint.sh"]

    # Comando padrão (manter container ativo)
    command: []

    labels:
      - "project=network-security-scanner"
      - "version=2.0"
      - "purpose=educational"
      - "maintainer=Network Security Scanner Team"

  # Serviço opcional para documentação (futuro)
  # docs:
  #   image: nginx:alpine
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - ./docs:/usr/share/nginx/html
  #   profiles:
  #     - docs

networks:
  default:
    driver: bridge